import Head from "next/head";
import Image from "next/image";
import Nav from "@/components/Nav";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Services from "@/components/Services";
import Choose from "@/components/Choose";
import Contact from "@/components/Contact";
import Goal from "@/components/Goal";
import Mission from "@/components/Mission";
import Target from "@/components/Target";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Excellent Research Consult</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main>
        <Hero />
        <About />
        <Services />
        <Goal />
        <Choose />
        <Target />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
